### PR TITLE
Fix: Month and Year not clickable on safari. 

### PR DESCRIPTION
**Pull request by bragento**
Hey there @dbrekalo, 

nice repo. Thank you for your aweseome work. 

Currently there is one problem on safari: 
If you click on month or year it will not open the select dropdown. 
It is because safari has a fixed size for those elements. 

If you add `-webkit-appearance` you can attach `width: 100%` and `height: 100%`.

### CODE REVIEW

**Comment by dbrekalo** [comment]
@bragento great work!

**Comment by bragento** [comment]
@dbrekalo thank you for the quick merge :) 

When do you plan to release it on npm?

**Comment by bragento** [comment]
@dbrekalo Hi there any updates? :)

**Comment by dbrekalo** [comment]
@bragento will try to publish it this week.

**Comment by janmarkuslanger** [comment]
@dbrekalo any updates? :)

**Pull request merged**
